FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder

ENV GO111MODULE=on \
    GOFLAGS=-mod=vendor

COPY . /go/src/github.com/operator-framework/operator-sdk
RUN cd /go/src/github.com/operator-framework/operator-sdk \
 && make -f ci/prow.Makefile patch build-coverage-helm-operator

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9

ENV HOME=/opt/helm \
    USER_NAME=helm \
    USER_UID=1001 \
    GOCOVERDIR=/tmp/e2e-cover

COPY --from=builder /go/src/github.com/operator-framework/operator-sdk/build/helm-operator /usr/local/bin/helm-operator
COPY release/helm/bin /usr/local/bin

RUN /usr/local/bin/user_setup

WORKDIR ${HOME}
USER ${USER_UID}
ENTRYPOINT ["/bin/sh", "-c", "mkdir -p /tmp/e2e-cover && exec /usr/local/bin/helm-operator run --watches-file=./watches.yaml"]
