---
name: CI

concurrency:
  group: linters-${{ github.ref }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - stable-*

jobs:
  linters:
    uses: ansible-network/github_actions/.github/workflows/tox-linters.yml@main