#!/usr/bin/env bash
# Copyright 2024 The Operator-SDK Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

set -o errexit
set -o nounset
set -o pipefail

ROOT="$(git rev-parse --show-toplevel)"
GO_BUILD_TAGS="containers_image_openpgp"

FILE="${1:-}"
if [[ -z "$FILE" ]]; then
  echo "Usage: $0 <go-file-path>" >&2
  exit 1
fi

# Resolve to absolute path relative to repo root
if [[ ! "$FILE" = /* ]]; then
  FILE="${ROOT}/${FILE}"
fi

if [[ ! -e "$FILE" ]]; then
  echo "Error: file not found: $FILE" >&2
  exit 1
fi

# Canonicalize both paths (resolving '..' segments and symlinks) and reject
# any file that resolves outside the repository root to prevent path
# traversal (e.g. FILE=../../etc/passwd.go).
FILE="$(realpath "$FILE")"
ROOT="$(realpath "$ROOT")"
TOOLS_DIR="${ROOT}/tools/bin"
case "$FILE" in
  "${ROOT}"/*) ;;
  *)
    echo "Error: file must be inside the repository ($ROOT)" >&2
    exit 1
    ;;
esac

if [[ ! -f "$FILE" ]]; then
  echo "Error: not a regular file: $FILE" >&2
  exit 1
fi

if [[ "$FILE" != *.go ]]; then
  echo "Error: only .go files are supported" >&2
  exit 1
fi

REL_PATH="${FILE#"${ROOT}"/}"

case "$REL_PATH" in
  vendor/*)           echo "Error: vendor/ files cannot be verified individually" >&2; exit 1 ;;
  testdata/*)         echo "Error: testdata/ files are generated — edit the generator instead" >&2; exit 1 ;;
  internal/bindata/*) echo "Error: internal/bindata/ files are generated — run 'make bindata'" >&2; exit 1 ;;
  *fakes/*)           echo "Error: fakes/ files are generated by counterfeiter" >&2; exit 1 ;;
esac

if [[ "$(basename "$REL_PATH")" == zz_generated* ]]; then
  echo "Error: zz_generated files are auto-generated" >&2
  exit 1
fi

cd "$ROOT"
PKG_PATH="./$(dirname "$REL_PATH")"

echo "==> Checking formatting..."
FMT_OUT="$(gofmt -l "$FILE")"
if [[ -n "$FMT_OUT" ]]; then
  echo "Error: file needs formatting: $FMT_OUT" >&2
  echo "Run: gofmt -w $REL_PATH" >&2
  exit 1
fi

echo "==> Running go vet on ${PKG_PATH}..."
go vet -tags="${GO_BUILD_TAGS}" "${PKG_PATH}"

echo "==> Running golangci-lint on ${PKG_PATH}..."
if [[ ! -x "${TOOLS_DIR}/golangci-lint" ]]; then
  make setup-lint
fi
"${TOOLS_DIR}/golangci-lint" run --build-tags "${GO_BUILD_TAGS}" "${PKG_PATH}"

echo "==> Running package tests (short mode)..."
go test -tags="${GO_BUILD_TAGS}" -short "${PKG_PATH}"

echo "==> All checks passed for ${REL_PATH}"
