name: commitlint
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false
    - uses: wagoid/commitlint-github-action@v6
      with:
        configFile: commitlint.config.js
