name: security
on:
  pull_request: {}
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"
    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
    - name: Run govulncheck
      run: govulncheck -tags containers_image_openpgp ./...

  osv-scan:
    name: osv-scan
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Run OSV Scanner
      uses: google/osv-scanner-action/osv-scanner-action@v2
      with:
        scan-args: |-
          --lockfile=go.sum

  image-scan:
    name: image-scan
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image:
          - operator-sdk
          - helm-operator
          - scorecard-test
          - scorecard-test-kuttl
          - custom-scorecard-tests
          - scorecard-untar
          - scorecard-storage
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    - name: Scan Dockerfile
      uses: aquasecurity/trivy-action@0.31.0
      with:
        scan-type: 'config'
        scan-ref: images/${{ matrix.image }}/Dockerfile
        severity: 'HIGH,CRITICAL'
        exit-code: '1'
